name: she_shield_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  flutter_sound: ^9.2.13
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.14
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  provider: ^6.1.2
  image_picker: ^1.0.7
  flutter_sms: ^2.3.3
  audioplayers: ^5.2.1
  geocoding: ^2.1.0
  path_provider: ^2.0.15
  http: ^1.2.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  


# name: she_shield_app
# description: Women's Safety App

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.2
#   permission_handler: ^11.1.0
#   flutter_sound: ^9.2.13
#   firebase_core: ^2.25.4
#   firebase_auth: ^4.17.4
#   cloud_firestore: ^4.15.4
#   firebase_storage: ^11.6.6
#   firebase_messaging: ^14.7.14
#   geolocator: ^10.1.0
#   google_maps_flutter: ^2.5.3
#   url_launcher: ^6.2.5
#   provider: ^6.1.2
#   image_picker: ^1.0.7
#   flutter_sms: ^2.3.3
#   audioplayers: ^5.2.1

# flutter:
#   assets:
#     - assets/sounds/siren.mp3


# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter:
#     uses-material-design: true






